# Generated by Django 5.0.6 on 2026-09-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('phone', 'Phone')], default='online', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Required for online interviews')),
                ('location', models.CharField(blank=True, help_text='Required for in-person interviews', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Instructions for the candidate (what to bring, round details, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='applications.application')),
            ],
        ),
    ]
