# Generated by Django 5.0.6 on 2026-09-18 06:10

import django.db.models.deletion
import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='pdf or docx', max_length=10)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('extraction_error', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='candidates.candidateprofile')),
            ],
        ),
    ]
